name: LaravelEscuela

on:
  push:
    branches: [feature/cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.3']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Check PHP
        run: php -v

      - uses: actions/checkout@v2

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: run composer install
        run: composer install -n --prefer-dist

      - name: Run Laravel pint
        run: ./vendor/bin/pint

      - name: Run script
        run: |
          echo "Hola mundo"
          ls
          echo "Fin"

